DROP TABLE player;
DROP TABLE player_profile;

CREATE TABLE player (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   LOGIN_NAME NVARCHAR(50) NOT NULL,
   LOGIN_PASSWORD NVARCHAR(200) NOT NULL,
   BALANCE DOUBLE NOT NULL,
   TOKEN NVARCHAR(500) NOT NULL
);

CREATE TABLE player_profile (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   PLAYER_ID INT NOT NULL,
   FIRST_NAME NVARCHAR(100) NOT NULL,
   LAST_NAME NVARCHAR(100) NOT NULL,
   FOREIGN KEY (PLAYER_ID) REFERENCES player (ID) on delete cascade on update cascade
);